# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
# Indentation needs to be set with spaces, because YAML...
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API endpoint to save pack stats

Globals:
    Api:
        # API Gateway regional endpoints
        EndpointConfiguration: EDGE
        Cors:
            AllowMethods: "'*'"
            AllowHeaders: "'*'"
            AllowOrigin: "'*'"

Resources:
    PopulatePackStatsFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: save-pack-stats.default
            Runtime: nodejs8.10
            Timeout: 90
            CodeUri: ./dist/save-pack-stats
            MemorySize: 512
            Policies:
                - AWSLambdaVPCAccessExecutionRole
                - AmazonSESFullAccess
                - SecretsManagerReadWrite
            Events:
                GetResource:
                    Type: Api
                    Properties:
                        Path: /{proxy+}
                        Method: any

Outputs:
    PopulatePackStatsApi:
        Description: URL to post pack stats
        Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/packstats'
        Export:
            Name: PopulatePackStatsApi
